/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_nvZPygBkz',
  aws_user_pools_web_client_id: '2kmn4m046e9kvjsa7dlpmde8an',
  oauth: {
    domain: 'mts-amplify-salesforce.auth.us-west-2.amazoncognito.com',
  },
  aws_appsync_graphqlEndpoint:
    'https://hbln2g6gj5bqhczgczghxixj6u.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
